import { build } from 'esbuild';
import { fileURLToPath } from 'node:url';

// Match the gallery's existing Three.js r185. Bundle only the add-on code used
// by GLTFLoader; share the existing Three.js modules already in the page.
await build({
  entryPoints: [fileURLToPath(new URL('node_modules/three/examples/jsm/loaders/GLTFLoader.js', import.meta.url))],
  outfile: fileURLToPath(new URL('../../content/static-sites/zannenin/manzokukyo-preview/vendor/GLTFLoader.js', import.meta.url)),
  bundle: true, minify: true, format: 'esm', target: 'es2022',
  banner: { js: '/*! Three.js r185 GLTFLoader + required utilities. Copyright 2010-2026 Three.js Authors. MIT License; see ./LICENSE. Generated by tools/gallery-models/prepare-loader.mjs. */' },
  plugins: [{ name: 'shared-three', setup(build) {
    build.onResolve({ filter: /^three$/ }, () => ({ path: './three.module.js', external: true }));
  } }],
});
